### ISSUE TITLE
Simpler bundle

### ISSUE THREAD

**Issue by dariocravero** [meyer-archives/react-css-property-operations#1]
Hi,

I built a standalone version of this react library at https://github.com/viewsdx/only-react-css-property-operations because I was having some issues trying to run this package with react 16.

`only-react-css-property-operations` has all the files in place and passed through rollup which results in a smaller bundle.

The name in this package is way more accurate though. Would you consider merging the two?
Thanks!
Darío

**Comment by meyer** [comment]
@dariocravero sorry for the very late reply. This NPM package is a dependency for one of our internal packages and we wouldn’t be able to transfer the package name. Apologies for squatting on the name. In retrospect, we should’ve published this package as a scoped package.
